 - name: PLAY-01
   hosts: web
   tasks:
   - name: PLAY-01 TASK-01
     ansible.builtin.debug:
    
     name: PLAY-02
   hosts: web
   tasks:
   - name: PLAY-02 TASK-02
     ansible.builtin.debug:
    