- name: Variables to print
  hosts: web
  tasks:
    - name: Print the information
      ansible.builtin.debug:
        msg: "10 12 14\"15"

    - name: Print a new message with variables
      vars:
        my_name: "vamshi"
        my_age: 24
      ansible.builtin.debug:
        msg: "Hello, my name is {{ my_name }} and I am {{ my_age }} years old."
