- name: variables to print
  hosts: web
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "10 12 14\"15"

        - name: print a new message with variables
        vars:
        my_name: "vamshi"
        my_age: 24
    tasks:
      - name: print variables
      ansible.builtin.debug:
      msg:  "hello, my name is {{my_name}} and i am {{my_age}} years old."        

