- name: expand practice with variables in ansible
  hosts: web
  vars:
    course_name: "basic devops"
    duration: "4 days"
  tasks:
  - name: print the course name
    ansible.builtin.deburg:
      msg: "the course name is {{course_name}}"
      
