- name: check a number is less than 10 or not
  hosts: local 
  condition: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
 tasks:
-  name: print this if less than 10
   ansible.builtin.debug:
     msg: "given number {{ number }} is less than 10"
   when:  number  < 10

   -  name: print this if greater than or equal to 10
   ansible.builtin.debug:
     msg: "given number {{ number }} is less than 10"
   when:  number  >= 10

